import pyautogui

pyautogui.press("win")
pyautogui.sleep(1)
pyautogui.write("google")
pyautogui.sleep(1)
pyautogui.press("ENTER")
pyautogui.sleep(1)
pyautogui.click(805,616)
pyautogui.sleep(1)
pyautogui.click(664,428)
pyautogui.sleep(1)
pyautogui.write("facebook")
pyautogui.sleep(1)
pyautogui.press("ENTER")
pyautogui.sleep(1)
pyautogui.click(805,616)
pyautogui.sleep(1)
pyautogui.click(317,365)